language: python
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- nightly
script: python test.py
deploy:
  provider: pypi
  user: ultrara1n
  password:
    secure: aig25xkDHPf4XaKMbvoivfZapGWkncoIvq3mdXsxnbINFm5m+fo5s5EIa/pbayzhBuRkoufTJ1wuj3TglLD/N+26E/Yb/dbzxEnobBlj8Vj32LLQKaEumMQ1VGCbdUL6AML15GnrW9dHZGsRCNQbhOeq4qx1KIcvihW4ZBYENeZkXXlXg5/cIS3LWrtNm9CoZba5QWF3jhafo/PJCp1vyGpwTZxIdCixeyNdnD1GtvyFX+kb20DrzRqlxc3SmUEuBRWhcp9v/mpht+Xz9gSJ88YfbU80tVG6nepKRO8aGug5FcpVaHAKPW6lZQDuMlFCdhSqokyF+hKqv4wOvqshrRFA8p2zl0GfESFSuE1OXMZW9XqnuCSUUp0oPvvUrc+4JQz+oaVWzXVrm7QnuvfLkcMgqBh9R5Ul0s2FCsbc60vdh8l21v71BhsvBWWPo025jPdwiHQdh+gyjzTQykVjkwnT2GqwutBau9SmwNxMz9ow25rdd1/ZnffsPp9uqxDrYtk5OIBU2fftbcggMVDPfNbcUqaxhFIdKSnom5qZPnukEfgw44E6rcDsr+VtiBr7ibm6Ky2AE4U3ohcpU+T605dY/Kh35oy2IlSXM4WyB83+IkK1LSpuCrESYUcph10eyAR1a2/nlYn2UZ6D2JXPwaqk6hoaB7vh1FwZ80e9Eew=
  on:
    tags: true
